Better verification of DESTROOT

diff --git a/usr/lib/zap/add-locale b/usr/lib/zap/add-locale
--- a/usr/lib/zap/add-locale
+++ b/usr/lib/zap/add-locale
@@ -35,6 +35,10 @@ case $1 in
 	CTXARGS="-C ${DESTROOT}"
 	shift
 	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
 	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
 	    echo "ERROR: alternate root $DESTROOT is invalid"
 	    exit 1
@@ -48,6 +52,10 @@ case $1 in
 	PKGARGS="-R ${DESTROOT}"
 	shift
 	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
 	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
 	    echo "ERROR: alternate root $DESTROOT is invalid"
 	    exit 1
diff --git a/usr/lib/zap/delpkg b/usr/lib/zap/delpkg
--- a/usr/lib/zap/delpkg
+++ b/usr/lib/zap/delpkg
@@ -15,7 +15,7 @@
 #
 # }}}
 #
-# Copyright 2024 Peter Tribble
+# Copyright 2025 Peter Tribble
 #
 
 #
@@ -40,6 +40,10 @@ case $1 in
     BFLAGS="-R ${DESTROOT}"
     shift
     shift
+    if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	echo "ERROR: alternate root $DESTROOT is invalid"
+	exit 1
+    fi
     ;;
 esac
 
diff --git a/usr/lib/zap/install-recursive b/usr/lib/zap/install-recursive
--- a/usr/lib/zap/install-recursive
+++ b/usr/lib/zap/install-recursive
@@ -15,7 +15,7 @@
 #
 # }}}
 #
-# Copyright 2024 Peter Tribble
+# Copyright 2025 Peter Tribble
 #
 
 #
@@ -69,6 +69,10 @@ case $1 in
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
 	    exit 1
 	fi
+	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	    echo "ERROR: alternate root $DESTROOT is invalid"
+	    exit 1
+	fi
 	INSTODIR="${DESTROOT}/${ODIR}"
 	OVLARGS="-C ${DESTROOT}"
 	;;
@@ -81,6 +85,10 @@ case $1 in
 	shift
 	if [ ! -d "$DESTROOT" ]; then
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	    echo "ERROR: alternate root $DESTROOT is invalid"
 	    exit 1
 	fi
 	INSTODIR="${DESTROOT}/${ODIR}"
diff --git a/usr/lib/zap/instzap b/usr/lib/zap/instzap
--- a/usr/lib/zap/instzap
+++ b/usr/lib/zap/instzap
@@ -40,6 +40,14 @@ case $1 in
     BFLAGS="-R ${DESTROOT}"
     shift
     shift
+    if [ ! -d "$DESTROOT" ]; then
+	echo "ERROR: alternate root $DESTROOT doesn't exist"
+	exit 1
+    fi
+    if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	echo "ERROR: alternate root $DESTROOT is invalid"
+	exit 1
+    fi
     ;;
 esac
 
diff --git a/usr/lib/zap/psearch b/usr/lib/zap/psearch
--- a/usr/lib/zap/psearch
+++ b/usr/lib/zap/psearch
@@ -15,7 +15,7 @@
 #
 # }}}
 #
-# Copyright 2024 Peter Tribble
+# Copyright 2025 Peter Tribble
 #
 
 #
@@ -31,12 +31,16 @@
 DESTROOT=""
 
 case $1 in
--R)
+-R|-C)
 	DESTROOT="$2"
 	shift
 	shift
 	if [ ! -d "$DESTROOT" ]; then
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	    echo "ERROR: alternate root $DESTROOT is invalid"
 	    exit 1
 	fi
 	;;
diff --git a/usr/lib/zap/resolve-alias b/usr/lib/zap/resolve-alias
--- a/usr/lib/zap/resolve-alias
+++ b/usr/lib/zap/resolve-alias
@@ -15,20 +15,24 @@
 #
 # }}}
 #
-# Copyright 2024 Peter Tribble
+# Copyright 2025 Peter Tribble
 #
 
 CFGDIR="/etc/zap"
 ZAPLIBDIR="/usr/lib/zap"
 
 case $1 in
--C)
+-R|-C)
 	DESTROOT="$2"
 	CTXARGS="-C ${DESTROOT}"
 	shift
 	shift
 	if [ ! -d "$DESTROOT" ]; then
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	    echo "ERROR: alternate root $DESTROOT is invalid"
 	    exit 1
 	fi
 	CFGDIR="${DESTROOT}/${CFGDIR}"
diff --git a/usr/lib/zap/set-hostname b/usr/lib/zap/set-hostname
--- a/usr/lib/zap/set-hostname
+++ b/usr/lib/zap/set-hostname
@@ -15,7 +15,7 @@
 #
 # }}}
 #
-# Copyright 2024 Peter Tribble
+# Copyright 2025 Peter Tribble
 #
 
 #
@@ -33,6 +33,10 @@ case $1 in
     shift
     if [ ! -d "$DESTROOT" ]; then
 	echo "ERROR: alternate root $DESTROOT doesn't exist"
+	exit 1
+    fi
+    if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	echo "ERROR: alternate root $DESTROOT is invalid"
 	exit 1
     fi
     ;;
diff --git a/usr/lib/zap/update-overlay b/usr/lib/zap/update-overlay
--- a/usr/lib/zap/update-overlay
+++ b/usr/lib/zap/update-overlay
@@ -38,6 +38,10 @@ case $1 in
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
 	    exit 1
 	fi
+	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	    echo "ERROR: alternate root $DESTROOT is invalid"
+	    exit 1
+	fi
 	CFGODIR="${DESTROOT}/${ODIR}"
 	INSTODIR="${DESTROOT}/${ODIR}"
 	;;
@@ -51,6 +55,10 @@ case $1 in
 	shift
 	if [ ! -d "$DESTROOT" ]; then
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	if [ ! -d "$DESTROOT/var/sadm/pkg" ]; then
+	    echo "ERROR: alternate root $DESTROOT is invalid"
 	    exit 1
 	fi
 	INSTODIR="${DESTROOT}/${ODIR}"
