Add proxy zones

diff --git a/usr/lib/zap/create-zone b/usr/lib/zap/create-zone
--- a/usr/lib/zap/create-zone
+++ b/usr/lib/zap/create-zone
@@ -8,6 +8,7 @@
 #  -z zone_name - zone name [required]
 #  -i IPv4 address [can be multiple, for shared-ip]
 #  -x IPv4 address [can be multiple, for exclusive-ip]
+#  -R Ipv4 network to proxy, in CIDR notation
 #  -I iso image for alien zone
 #  -d directory to create [can be multiple]
 #  -o overlay for partial root [can be multiple, passed to install]
@@ -19,7 +20,6 @@
 # add IPv6
 # add appstack overlays for sparse zones
 # inherit dirs (like I do for sfw)
-# dedicated stack and vnic creation
 #
 
 ZFSBASE="/export/zonedata"
@@ -29,6 +29,9 @@ ZBRAND=TRIBsparse
 ZNAME=""
 ZIP4=""
 XIP4=""
+RIP4=""
+NRIP4=""
+ORIP4=""
 ZISOFILE=""
 ZOVERLAY=""
 ZADDOVERLAY=""
@@ -37,14 +40,21 @@ ZUSERS=""
 ZTEMPLATE=""
 ZBLANK=""
 
+#
+# these associative arrays track the interface to address mapping
+#
+typeset -A ifipmap
+typeset -A xifipmap
+
 usage() {
   echo "Usage: $0 -z zone_name [-t whole|sparse|alien]"
-  echo "  [-T template] [-I iso_image] [-i ip_address] [-x ip_address]"
+  echo "  [-T template] [-I iso_image]"
+  echo "  [-i ip_address] [-x ip_address] [-R ip_network/prefix]"
   echo "  [-B] [-d extra_dir] [-o overlay] [-O overlay] [-U user]"
   exit 1
 }
 
-while getopts "BT:t:z:i:x:I:o:O:d:U:" opt; do
+while getopts "BT:t:z:i:x:R:I:o:O:d:U:" opt; do
 case $opt in
 B)
 	ZBLANK="Y"
@@ -63,6 +73,9 @@ i)
 	;;
 x)
 	XIP4="${XIP4} $OPTARG"
+	;;
+R)
+	RIP4="${RIP4} $OPTARG"
 	;;
 I)
 	ZISOFILE="$OPTARG"
@@ -169,6 +182,24 @@ if [[ -n $XIP4 && -n $ZIP4 ]]; then
 fi
 
 #
+# if the zone is a router/proxy (-R option) then the primary interface
+# must be of type exclusive, not shared, a primary interface must be
+# defined, and the zone type must not be alien
+#
+if [[ -n $RIP4 && -n $ZIP4 ]]; then
+    echo "ERROR: proxy zones require -x, not -i"
+    usage
+fi
+if [[ -n $RIP4 && -z $XIP4 ]]; then
+    echo "ERROR: proxy zones require a primary interface be specified with -x"
+    usage
+fi
+if [[ -n $RIP4 && $ZBRAND = TRIBalien ]]; then
+    echo "ERROR: proxy zones must not be of type alien"
+    usage
+fi
+
+#
 # check if the zone already exists
 #
 /usr/sbin/zoneadm -z $ZNAME list > /dev/null 2>&1
@@ -176,6 +207,123 @@ ZEXISTS=$?
 if [ $ZEXISTS -eq 0 ]; then
     echo "ERROR: zone $ZNAME already exists"
     exit 1
+fi
+
+#
+# for any routing/proxy, verify we're being given sensible information
+# It must look like a.b.c.d/n, and d must be zero
+# rewrite addresses from the network address to the host address of .1
+# check no other zone is routing this network
+#
+if [[ -n $RIP4 ]]; then
+    for RIP in $RIP4
+    do
+	case $RIP in
+	    *.*.*.*.*)
+		echo "Invalid proxy network $RIP"
+		echo "  Expected a.b.c.d/prefix"
+		exit 2
+		;;
+	    */*/*)
+		echo "Invalid proxy network $RIP"
+		echo "  Expected a.b.c.d/prefix"
+		exit 2
+		;;
+	    *.*.*.*/*)
+		RPREFIX=${RIP##*/}
+		RSUBNET=${RIP%/*}
+		echo $RSUBNET | tr '.' ' '|read OCT1 OCT2 OCT3 OCT4
+		if [ $OCT1 -lt 1 -o $OCT1 -gt 223 ]; then
+		    echo "Invalid proxy network $RIP"
+		    echo "  first octet $OCT1 out of range"
+		    exit 2
+		fi
+		if [ $OCT2 -lt 0 -o $OCT2 -gt 255 ]; then
+		    echo "Invalid proxy network $RIP"
+		    echo "  second octet $OCT2 out of range"
+		    exit 2
+		fi
+		if [ $OCT3 -lt 0 -o $OCT3 -gt 255 ]; then
+		    echo "Invalid proxy network $RIP"
+		    echo "  third octet $OCT3 out of range"
+		    exit 2
+		fi
+		if [ $OCT4 -ne 0 ]; then
+		    echo "Invalid proxy network $RIP"
+		    echo "  fourth octet $OCT4 out of range, must be 0"
+		    exit 2
+		fi
+		case $RPREFIX in
+		    8)
+			if [ $OCT2 -ne 0 ]; then
+			    echo "Invalid proxy network $RIP"
+			    echo "  second octet $OCT2 out of range, must be zero for /8"
+			    exit 2
+			fi
+			if [ $OCT3 -ne 0 ]; then
+			    echo "Invalid proxy address $RIP"
+			    echo "  third octet $OCT3 out of range, must be zero for /8"
+			    exit 2
+			fi
+			if [ -f ${ZSDIR}/rconfig.${OCT1} ]; then
+			    ZOWNER=`/usr/bin/grep zone: ${ZSDIR}/rconfig.${OCT1} | /usr/bin/awk '{print $NF}'`
+			    echo "ERROR: network $RIP is already in use by zone $ZOWNER"
+			    exit 2
+			fi
+			NRIP4="$NRIP4 ${OCT1}.${OCT2}.${OCT3}.1/${RPREFIX}"
+			;;
+		    16)
+			if [ $OCT3 -ne 0 ]; then
+			    echo "Invalid proxy address $RIP"
+			    echo "  third octet $OCT3 out of range, must be zero for /16"
+			    exit 2
+			fi
+			if [ -f ${ZSDIR}/rconfig.${OCT1} ]; then
+			    ZOWNER=`/usr/bin/grep zone: ${ZSDIR}/rconfig.${OCT1} | /usr/bin/awk '{print $NF}'`
+			    echo "ERROR: parent network ${OCT1}.0.0.0/8 for $RIP is already in use by zone $ZOWNER"
+			    exit 2
+			fi
+			if [ -f ${ZSDIR}/rconfig.${OCT1}.${OCT2} ]; then
+			    ZOWNER=`/usr/bin/grep zone: ${ZSDIR}/rconfig.${OCT1}.${OCT2} | /usr/bin/awk '{print $NF}'`
+			    echo "ERROR: network $RIP is already in use by zone $ZOWNER"
+			    exit 2
+			fi
+			NRIP4="$NRIP4 ${OCT1}.${OCT2}.${OCT3}.1/${RPREFIX}"
+			;;
+		    24)
+			if [ -f ${ZSDIR}/rconfig.${OCT1} ]; then
+			    ZOWNER=`/usr/bin/grep zone: ${ZSDIR}/rconfig.${OCT1} | /usr/bin/awk '{print $NF}'`
+			    echo "ERROR: parent network ${OCT1}.0.0.0/8 for $RIP is already in use by zone $ZOWNER"
+			    exit 2
+			fi
+			if [ -f ${ZSDIR}/rconfig.${OCT1}.${OCT2} ]; then
+			    ZOWNER=`/usr/bin/grep zone: ${ZSDIR}/rconfig.${OCT1}.${OCT2} | /usr/bin/awk '{print $NF}'`
+			    echo "ERROR: parent network ${OCT1}.${OCT2}.0.0/16 for $RIP is already in use by zone $ZOWNER"
+			    exit 2
+			fi
+			if [ -f ${ZSDIR}/rconfig.${OCT1}.${OCT2}.${OCT3} ]; then
+			    ZOWNER=`/usr/bin/grep zone: ${ZSDIR}/rconfig.${OCT1}.${OCT2}.${OCT3} | /usr/bin/awk '{print $NF}'`
+			    echo "ERROR: network $RIP is already in use by zone $ZOWNER"
+			    exit 2
+			fi
+			NRIP4="$NRIP4 ${OCT1}.${OCT2}.${OCT3}.1/${RPREFIX}"
+			;;
+		    *)
+			echo "Invalid proxy prefix /$RPREFIX"
+			echo "  Supported values: /8 /16 /24"
+			exit 2
+			;;
+		esac
+		;;
+	    *)
+		echo "Invalid proxy address $RIP"
+		echo "  Expected a.b.c.d/prefix"
+		exit 2
+		;;
+	esac
+    done
+    ORIP4=$RIP4
+    RIP4=$NRIP4
 fi
 
 #
@@ -275,6 +423,83 @@ done
 echo $CIDR
 }
 
+#
+# return interface and cidr prefix for the given address
+#
+get_net_details() {
+    IIP=$1
+    NIP=`get_short_net ${IIP}/24`
+    if [ -f ${ZSDIR}/rconfig.${NIP} ] ; then
+	IFACE=`/usr/bin/grep interface: ${ZSDIR}/rconfig.${NIP} | /usr/bin/awk '{print $NF}'`
+	ICIDR=24
+	echo "$IFACE $ICIDR"
+	return
+    fi
+    NIP=`get_short_net ${IIP}/16`
+    if [ -f ${ZSDIR}/rconfig.${NIP} ] ; then
+	IFACE=`/usr/bin/grep interface: ${ZSDIR}/rconfig.${NIP} | /usr/bin/awk '{print $NF}'`
+	ICIDR=16
+	echo "$IFACE $ICIDR"
+	return
+    fi
+    NIP=`get_short_net ${IIP}/8`
+    if [ -f ${ZSDIR}/rconfig.${NIP} ] ; then
+	IFACE=`/usr/bin/grep interface: ${ZSDIR}/rconfig.${NIP} | /usr/bin/awk '{print $NF}'`
+	ICIDR=8
+	echo "$IFACE $ICIDR"
+	return
+    fi
+    IFACE=`/usr/sbin/route -n get $IIP | /usr/bin/grep interface: | /usr/bin/awk '{print $NF}'`
+    IMASK=`/usr/sbin/route -n get $IIP | /usr/bin/grep mask: | /usr/bin/awk '{print $NF}'`
+    ICIDR=`get_mask $IMASK`
+    echo "$IFACE $ICIDR"
+}
+
+#
+# return the default gateway for the given address
+#
+get_gateway() {
+    IIP=$1
+    NIP=`get_short_net ${IIP}/24`
+    if [ -f ${ZSDIR}/rconfig.${NIP} ] ; then
+	/usr/bin/grep gateway: ${ZSDIR}/rconfig.${NIP} | /usr/bin/awk '{print $NF}'
+	return
+    fi
+    NIP=`get_short_net ${IIP}/16`
+    if [ -f ${ZSDIR}/rconfig.${NIP} ] ; then
+	/usr/bin/grep gateway: ${ZSDIR}/rconfig.${NIP} | /usr/bin/awk '{print $NF}'
+	return
+    fi
+    NIP=`get_short_net ${IIP}/8`
+    if [ -f ${ZSDIR}/rconfig.${NIP} ] ; then
+        /usr/bin/grep gateway: ${ZSDIR}/rconfig.${NIP} | /usr/bin/awk '{print $NF}'
+	return
+    fi
+    /usr/sbin/route -n get default | /usr/bin/grep gateway: | /usr/bin/awk '{print $NF}'
+}
+
+#
+# return the short form of the network address - just the significant octets
+# we only support /8 /16 /24 for router/proxy zones so no need to check
+#
+get_short_net() {
+    IIP=$1
+    SRPREFIX=${IIP##*/}
+    SRSUBNET=${IIP%/*}
+    echo $SRSUBNET | tr '.' ' '|read OCT1 OCT2 OCT3 OCT4
+    case $SRPREFIX in
+	8)
+	    echo "${OCT1}"
+	    ;;
+	16)
+	    echo "${OCT1}.${OCT2}"
+	    ;;
+	24)
+	    echo "${OCT1}.${OCT2}.${OCT3}"
+	    ;;
+    esac
+}
+
 create_configuration() {
 echo create -t $ZBRAND
 echo set autoboot=true
@@ -287,9 +512,7 @@ fi
 #
 for IP in $ZIP4
 do
-	ZIFACE=`/usr/sbin/route -n get $IP | /usr/bin/grep interface: | /usr/bin/awk '{print $NF}'`
-	ZMASK=`/usr/sbin/route -n get $IP | /usr/bin/grep mask: | /usr/bin/awk '{print $NF}'`
-	ZCIDR=`get_mask $ZMASK`
+	get_net_details $IP | read ZIFACE ZCIDR
 	echo add net
 	echo set physical=$ZIFACE
 	echo set address=${IP}/${ZCIDR}
@@ -298,8 +521,7 @@ done
 #
 # exclusive-ip addresses
 # the address is used to construct the topology, it's up to the
-# zone to manage it (if using dhcp, then any address on the correct
-# subnet will do the right thing)
+# zone to manage it, but we set up a valid hostname file
 #
 # we set up the vnic here, and save details so that we can remove it
 # when the zone is destroyed
@@ -307,7 +529,7 @@ done
 ZENUM=0
 for IP in $XIP4
 do
-	ZIFACE=`/usr/sbin/route -n get $IP | /usr/bin/grep interface: | /usr/bin/awk '{print $NF}'`
+	get_net_details $IP | read ZIFACE ZCIDR
 	/usr/sbin/dladm show-vnic znic$ZENUM > /dev/null 2>&1
 	ZESTATUS=$?
 	while [ $ZESTATUS -eq 0 ]
@@ -325,9 +547,58 @@ do
 	    /usr/bin/chmod a+x ${ZSDIR}/destroy.${ZNAME}
 	fi
 	echo "/usr/sbin/dladm delete-vnic znic$ZENUM" >> ${ZSDIR}/destroy.${ZNAME}
+	ifipmap[znic$ZENUM]=$IP/$ZCIDR
+	xifipmap[znic$ZENUM]=$IP/$ZCIDR
 	echo add net
 	echo set physical=znic$ZENUM
 	echo end
+done
+#
+# For router/proxy zones we create an etherstub for the internal virtual
+# network, and create a vnic over that etherstub. The router/proxy zone
+# will have the matching .1 address on that network.
+#
+# Note that the destroy script must have been initialized above as we
+# require a router/proxy zone to have an exclusive-ip address, and we
+# carry on enumerating ZENUM where we left off
+#
+ZRNUM=0
+ZENUM=$(($ZENUM+1))
+for IP in $RIP4
+do
+	/usr/sbin/dladm show-etherstub zrstub$ZRNUM > /dev/null 2>&1
+	ZRSTATUS=$?
+	while [ $ZRSTATUS -eq 0 ]
+	do
+	    ZRNUM=$(($ZRNUM+1))
+	    /usr/sbin/dladm show-etherstub zrstub$ZRNUM > /dev/null 2>&1
+	    ZRSTATUS=$?
+	done
+	ZIFACE=zrstub$ZRNUM
+	/usr/sbin/dladm create-etherstub $ZIFACE
+	/usr/sbin/dladm show-vnic znic$ZENUM > /dev/null 2>&1
+	ZESTATUS=$?
+	while [ $ZESTATUS -eq 0 ]
+	do
+	    ZENUM=$(($ZENUM+1))
+	    /usr/sbin/dladm show-vnic znic$ZENUM > /dev/null 2>&1
+	    ZESTATUS=$?
+	done
+	/usr/sbin/dladm create-vnic -l $ZIFACE znic$ZENUM
+	echo "/usr/sbin/dladm delete-vnic znic$ZENUM" >> ${ZSDIR}/destroy.${ZNAME}
+	# delete the etherstub after the vnic configured on it
+	echo "/usr/sbin/dladm delete-etherstub $ZIFACE" >> ${ZSDIR}/destroy.${ZNAME}
+	ifipmap[znic$ZENUM]=$IP
+	echo add net
+	echo set physical=znic$ZENUM
+	echo end
+	# save the configuration here
+	ZNETNAME=`get_short_net $IP`
+	touch ${ZSDIR}/rconfig.${ZNETNAME}
+	echo "interface: $ZIFACE" >> ${ZSDIR}/rconfig.${ZNETNAME}
+	echo "gateway: ${IP%/*}" >> ${ZSDIR}/rconfig.${ZNETNAME}
+	echo "zone: ${ZNAME}" >> ${ZSDIR}/rconfig.${ZNETNAME}
+	echo "rm ${ZSDIR}/rconfig.${ZNETNAME}" >> ${ZSDIR}/destroy.${ZNAME}
 done
 for DIR in $ZDIRS
 do
@@ -407,6 +678,43 @@ do
     /usr/bin/grep "^${TUSER}:" /etc/shadow >> ${ZROOTBASE}/${ZNAME}/root/etc/shadow
     echo "${TUSER}::::roles=root" >> ${ZROOTBASE}/${ZNAME}/root/etc/user_attr
 done
+
+#
+# for exclusive-ip stacks:
+#  create /etc/hostname.* files for each vnic we created
+#  set the default route
+#
+for index in "${!ifipmap[@]}"
+do
+    echo "${ifipmap[$index]}" > ${ZROOTBASE}/${ZNAME}/root/etc/hostname.$index
+done
+if [[ -n $XIP4 ]]; then
+    ZGW=`get_gateway $XIP4`
+    echo $ZGW > ${ZROOTBASE}/${ZNAME}/root/etc/defaultrouter
+fi
+
+#
+# for router/proxy zones:
+#  configure nat for all subnets
+#  enable ip forwarding on all interfaces
+#
+if [[ -n $RIP4 ]]; then
+    touch ${ZROOTBASE}/${ZNAME}/root/etc/rc2.d/S83router
+    echo "#!/bin/sh" > ${ZROOTBASE}/${ZNAME}/root/etc/rc2.d/S83router
+    for index in "${!ifipmap[@]}"
+    do
+	echo "/usr/sbin/ipadm set-ifprop -t -p forwarding=on -m ipv4 $index" >> ${ZROOTBASE}/${ZNAME}/root/etc/rc2.d/S83router
+    done
+    echo /usr/sbin/svcadm enable network/ipfilter >> ${ZROOTBASE}/${ZNAME}/root/etc/rc2.d/S83router
+    chmod a+x ${ZROOTBASE}/${ZNAME}/root/etc/rc2.d/S83router
+    IFACE=`echo "${!xifipmap[@]}"|awk '{print $1}'`
+    touch ${ZROOTBASE}/${ZNAME}/root/etc/ipf/ipnat.conf
+    for subnet in $ORIP4
+    do
+	echo "map $IFACE $subnet -> 0/32 portmap tcp/udp auto" >> ${ZROOTBASE}/${ZNAME}/root/etc/ipf/ipnat.conf
+	echo "map $IFACE $subnet -> 0/32" >> ${ZROOTBASE}/${ZNAME}/root/etc/ipf/ipnat.conf
+    done
+fi
 
 #
 # blank the zone if requested; init requires the smf entry to be present in
