zone destroy needs to check the zone exists zones are only possible in the global zone cannot create or destroy the global zone check if new zone name is already in use

diff --git a/usr/lib/zap/create-zone b/usr/lib/zap/create-zone
--- a/usr/lib/zap/create-zone
+++ b/usr/lib/zap/create-zone
@@ -55,9 +55,23 @@ d)
 esac
 done
 
+THISZONE=`/sbin/zonename`
+if [ "X$THISZONE" != "Xglobal" ]; then
+    echo "ERROR: zone management is only possible in the global zone"
+    exit 1
+fi
+
 if [[ -z $ZNAME ]]; then
    echo "ERROR: zone name must be specified"
    usage
+fi
+
+#
+# you can't create the global zone
+#
+if [ "X$ZNAME" = "Xglobal" ]; then
+    echo "ERROR: global zone is reserved"
+    exit 1
 fi
 
 #
@@ -87,6 +101,16 @@ TRIBsparse)
 	fi
 	;;
 esac
+
+#
+# check if the zone already exists
+#
+/usr/sbin/zoneadm -z $ZNAME list > /dev/null 2>&1
+ZEXISTS=$?
+if [ $ZEXISTS -eq 0 ]; then
+    echo "ERROR: zone $ZNAME already exists"
+    exit 1
+fi
 
 #
 # construct a zone configuration file
diff --git a/usr/lib/zap/destroy-zone b/usr/lib/zap/destroy-zone
--- a/usr/lib/zap/destroy-zone
+++ b/usr/lib/zap/destroy-zone
@@ -12,14 +12,37 @@ z)
 esac
 done
 
-if [[ -z $ZNAME ]]; then
-   echo "ERROR: zone name must be specified"
-   exit 1
+THISZONE=`/sbin/zonename`
+if [ "X$THISZONE" != "Xglobal" ]; then
+    echo "ERROR: zone management is only possible in the global zone"
+    exit 1
 fi
 
-/usr/sbin/zoneadm -z $ZNAME halt
-echo "Halted zone $ZNAME"
-/usr/sbin/zoneadm -z $ZNAME uninstall -F
-echo "Uninstalled zone $ZNAME"
-/usr/sbin/zonecfg -z $ZNAME delete -F
-echo "Deleted zone $ZNAME"
+if [[ -z $ZNAME ]]; then
+    echo "ERROR: zone name must be specified"
+    exit 1
+fi
+
+#
+# it makes no sense to destroy the global zone
+#
+if [ "X$ZNAME" = "Xglobal" ]; then
+    echo "ERROR: unable to delete the global zone"
+    exit 1
+fi
+
+#
+# check it exists, otherwise behaviour is correct but messy
+#
+/usr/sbin/zoneadm -z $ZNAME list > /dev/null 2>&1
+ZEXISTS=$?
+if [ $ZEXISTS -eq 0 ]; then
+    /usr/sbin/zoneadm -z $ZNAME halt
+    echo "Halted zone $ZNAME"
+    /usr/sbin/zoneadm -z $ZNAME uninstall -F
+    echo "Uninstalled zone $ZNAME"
+    /usr/sbin/zonecfg -z $ZNAME delete -F
+    echo "Deleted zone $ZNAME"
+else
+    echo "ERROR: No such zone $ZNAME"
+fi
