Verify ZDPARENT is a valid dataset

diff --git a/usr/lib/zap/create-zone b/usr/lib/zap/create-zone
--- a/usr/lib/zap/create-zone
+++ b/usr/lib/zap/create-zone
@@ -2387,6 +2387,10 @@ fi
 if [[ -n ${ZDIRS} ]]; then
    ZPARENT=${ZFSBASE%/*}
    ZDPARENT=$(/usr/sbin/zfs list -H -o name "${ZPARENT}")
+   if [ -z "${ZDPARENT}" ]; then
+     echo "ERROR: cannot find zfs dataset for ${ZPARENT}"
+     exit 1
+   fi
    ZREALNAME=$(echo $ZFSBASE | /usr/bin/sed s:${ZPARENT}:${ZDPARENT}:)
    if [[ ! -d "${ZFSBASE}" ]]; then
       /usr/sbin/zfs create "${ZREALNAME}"
@@ -2398,6 +2402,10 @@ fi
 if [[ ! -d "${ZROOTBASE}" ]]; then
    ZPARENT=${ZROOTBASE%/*}
    ZDPARENT=$(/usr/sbin/zfs list -H -o name "${ZPARENT}")
+   if [ -z "${ZDPARENT}" ]; then
+     echo "ERROR: cannot find zfs dataset for ${ZPARENT}"
+     exit 1
+   fi
    ZREALNAME=$(echo $ZROOTBASE | /usr/bin/sed s:${ZPARENT}:${ZDPARENT}:)
    /usr/sbin/zfs create "${ZREALNAME}"
 fi
diff --git a/usr/lib/zap/create-zone-template b/usr/lib/zap/create-zone-template
--- a/usr/lib/zap/create-zone-template
+++ b/usr/lib/zap/create-zone-template
@@ -242,12 +242,17 @@ fi
 if [ ! -d "${ZROOTBASE}" ]; then
    ZPARENT=${ZROOTBASE%/*}
    ZDPARENT=$(/usr/sbin/zfs list -H -o name "${ZPARENT}")
+   if [ -z "${ZDPARENT}" ]; then
+     echo "ERROR: cannot locate zfs dataset for ${ZROOTBASE}"
+     exit 1
+   fi
    ZREALNAME=$(echo $ZROOTBASE | /usr/bin/sed s:${ZPARENT}:${ZDPARENT}:)
    /usr/sbin/zfs create "${ZREALNAME}"
 fi
 if [ ! -d "${ZROOTBASE}/${TNAME}" ]; then
    ZPARENT=${ZROOTBASE%/*}
    ZDPARENT=$(/usr/sbin/zfs list -H -o name "${ZPARENT}")
+   # we already checked for ZDPARENT being empty above
    ZREALNAME=$(echo $ZROOTBASE | /usr/bin/sed s:${ZPARENT}:${ZDPARENT}:)
    /usr/sbin/zfs create "${ZREALNAME}/${TNAME}"
 fi
diff --git a/usr/lib/zap/destroy-zone-template b/usr/lib/zap/destroy-zone-template
--- a/usr/lib/zap/destroy-zone-template
+++ b/usr/lib/zap/destroy-zone-template
@@ -76,6 +76,10 @@ fi
 # This is the backing zfs dataset
 #
 ZDPARENT=$(/usr/sbin/zfs list -H -o name "${UROOT}")
+if [ -z "${ZDPARENT}" ]; then
+  echo "ERROR: cannot find zfs dataset for template $TNAME"
+  exit 1
+fi
 
 #
 # Sanity check: the zfs dataset should end in the template name
