Support upgrades

diff --git a/usr/lib/zap/get-version b/usr/lib/zap/get-version
--- a/usr/lib/zap/get-version
+++ b/usr/lib/zap/get-version
@@ -4,6 +4,20 @@
 CFGDIR="/etc/zap"
 ZAPLIBDIR="/usr/lib/zap"
 
+case $1 in
+-C)
+	DESTROOT="$2"
+	CTXARGS="-C ${DESTROOT}"
+	shift
+	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	CFGDIR="${DESTROOT}/${CFGDIR}"
+	;;
+esac
+
 case $# in
 1)
 	PKG="$1"
@@ -17,7 +31,7 @@ esac
 # given an unqualified package, return a qualified package and the name
 # of the repo it's contained in
 #
-for repo in `${ZAPLIBDIR}/zap-cfg list-pkg-repos`
+for repo in `${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-pkg-repos`
 do
     if [ -f ${CFGDIR}/repositories/${repo}.catalog ]; then
 	FPKG=`/usr/bin/nawk -F'|' '{if ($1 == npkg) print $1"."$2}' npkg=${PKG} ${CFGDIR}/repositories/${repo}.catalog`
diff --git a/usr/lib/zap/install-overlay b/usr/lib/zap/install-overlay
--- a/usr/lib/zap/install-overlay
+++ b/usr/lib/zap/install-overlay
@@ -3,9 +3,27 @@
 ONAME=""
 ZAPLIBDIR="/usr/lib/zap"
 ODIR="/var/sadm/overlays"
+INSTODIR="S{ODIR}"
+CFGODIR="${ODIR}"
 PKGARGS=""
 DESTROOT=""
 SRCARGS=""
+
+case $1 in
+-C)
+	DESTROOT="$2"
+	PKGARGS="-R ${DESTROOT}"
+	CTXARGS="-C ${DESTROOT}"
+	shift
+	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	CFGODIR="${DESTROOT}/${ODIR}"
+	INSTODIR="${DESTROOT}/${ODIR}"
+	;;
+esac
 
 case $1 in
 -R)
@@ -17,6 +35,7 @@ case $1 in
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
 	    exit 1
 	fi
+	INSTODIR="${DESTROOT}/${ODIR}"
 	;;
 esac
 
@@ -39,39 +58,35 @@ case $# in
 	ONAME="$1"
 	;;
 *)
-	echo "Usage: $0 [-R alt-root] [-s pkg_source] overlay"
+	echo "Usage: $0 [-C|-R alt-root] [-s pkg_source] overlay"
 	exit 1
 	;;
 esac
 
 #
-# OK, we're in the installer
-#
-
-#
 # if installed, just exit
 # if someone has messed with packages behind our back, they suffer
 #
-if [ -f ${DESTROOT}/${ODIR}/installed/${ONAME} ]; then
+if [ -f ${INSTODIR}/installed/${ONAME} ]; then
     exit 0
 fi
 
-PLIST="${ODIR}/${ONAME}.pkgs"
+PLIST="${CFGODIR}/${ONAME}.pkgs"
 if [ ! -f "${PLIST}" ]; then
-    echo "ERROR: package list missing"
+    echo "ERROR: package list for overlay ${ONAME} missing"
     exit 1
 fi
 
 #
 # install dependent overlays, if any
 #
-OVL="${ODIR}/${ONAME}.ovl"
+OVL="${CFGODIR}/${ONAME}.ovl"
 for novl in `/usr/bin/grep '^REQUIRES=' ${OVL} | /usr/bin/sed s:REQUIRES=::`
 do
-    ${ZAPLIBDIR}/install-overlay ${PKGARGS} ${SRCARGS} ${novl}
+    ${ZAPLIBDIR}/install-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
 done
 
-${ZAPLIBDIR}/install-pkg ${PKGARGS} ${SRCARGS} `cat ${PLIST}`
+${ZAPLIBDIR}/install-pkg ${CTXARGS} ${PKGARGS} ${SRCARGS} `cat ${PLIST}`
 OVSUCCESS=$?
 
 #
@@ -79,8 +94,8 @@ OVSUCCESS=$?
 #
 if [ $OVSUCCESS -eq 0 ]; then
     echo "Overlay ${ONAME} installation succeeded"
-    mkdir -p ${DESTROOT}/${ODIR}/installed
-    touch ${DESTROOT}/${ODIR}/installed/${ONAME}
+    mkdir -p ${INSTODIR}/installed
+    touch ${INSTODIR}/installed/${ONAME}
 else
     echo "Errors in installation of overlay ${ONAME}"
 fi
diff --git a/usr/lib/zap/install-pkg b/usr/lib/zap/install-pkg
--- a/usr/lib/zap/install-pkg
+++ b/usr/lib/zap/install-pkg
@@ -7,6 +7,20 @@ NINSTALLED=0
 NFAILED=0
 
 case $1 in
+-C)
+	DESTROOT="$2"
+	PKGARGS="-R ${DESTROOT}"
+	CTXARGS="-C ${DESTROOT}"
+	shift
+	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	;;
+esac
+
+case $1 in
 -R)
 	DESTROOT="$2"
 	PKGARGS="-R ${DESTROOT}"
@@ -19,7 +33,7 @@ case $1 in
 	;;
 esac
 
-SRCLIST=`${ZAPLIBDIR}/zap-cfg cache-dir`
+SRCLIST=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir`
 
 #
 # prepend the given source to the list, so it gets searched first
@@ -59,7 +73,7 @@ do
   FOUNDPKG=$?
   if [ $FOUNDPKG -ne 0 ]; then
     ISINST="false"
-    fpkg=`${ZAPLIBDIR}/get-version $pkg | /usr/bin/awk '{print $1}'`
+    fpkg=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | /usr/bin/awk '{print $1}'`
     for SRCDIR in $SRCLIST
     do
 	if [ -f ${SRCDIR}/${fpkg}.zap ]; then
@@ -72,7 +86,7 @@ do
     done
     # download if we don't have it yet
     if [ "$ISINST" = "false" ]; then
-	${ZAPLIBDIR}/retrieve-pkg ${pkg}
+	${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} ${pkg}
     fi
   fi
 done
@@ -88,7 +102,7 @@ do
     echo "Package $pkg already installed"
   else
     ISINST="false"
-    fpkg=`${ZAPLIBDIR}/get-version $pkg | /usr/bin/awk '{print $1}'`
+    fpkg=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | /usr/bin/awk '{print $1}'`
     for SRCDIR in $SRCLIST
     do
 	if [ -f ${SRCDIR}/${fpkg}.zap ]; then
diff --git a/usr/lib/zap/refresh-catalog b/usr/lib/zap/refresh-catalog
--- a/usr/lib/zap/refresh-catalog
+++ b/usr/lib/zap/refresh-catalog
@@ -6,9 +6,27 @@
 ZAPLIBDIR="/usr/lib/zap"
 CFGDIR="/etc/zap"
 
+#
+# global context switch
+# will force all configuration to be relative to the alternate root
+#
+case $1 in
+-C)
+	ALTROOT="$2"
+	CTXARGS="-C ${ALTROOT}"
+	shift
+	shift
+	if [ ! -d "$ALTROOT" ]; then
+	    echo "ERROR: alternate root $ALTROOT doesn't exist"
+	    exit 1
+	fi
+	CFGDIR="${ALTROOT}/${CFGDIR}"
+	;;
+esac
+
 refresh_repo() {
     frepo="$1"
-    REPO=`${ZAPLIBDIR}/zap-cfg repo-url $frepo`
+    REPO=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} repo-url $frepo`
     /usr/bin/curl -f -s -o ${CFGDIR}/repositories/${frepo}.catalog.tmp ${REPO}/catalog
     if [ -s ${CFGDIR}/repositories/${frepo}.catalog.tmp ]; then
 	mv ${CFGDIR}/repositories/${frepo}.catalog ${CFGDIR}/repositories/${frepo}.catalog.bak
diff --git a/usr/lib/zap/refresh-overlays b/usr/lib/zap/refresh-overlays
--- a/usr/lib/zap/refresh-overlays
+++ b/usr/lib/zap/refresh-overlays
@@ -8,16 +8,35 @@ CFGDIR="/etc/zap"
 ODIR="/var/sadm/overlays"
 UPDATED="no"
 
+#
+# global context switch
+# will force all configuration to be relative to the alternate root
+#
+case $1 in
+-C)
+	ALTROOT="$2"
+	CTXARGS="-C ${ALTROOT}"
+	shift
+	shift
+	if [ ! -d "$ALTROOT" ]; then
+	    echo "ERROR: alternate root $ALTROOT doesn't exist"
+	    exit 1
+	fi
+	CFGDIR="${ALTROOT}/${CFGDIR}"
+	ODIR="${ALTROOT}/${ODIR}"
+	;;
+esac
+
 refresh_repo() {
     frepo="$1"
-    REPO=`${ZAPLIBDIR}/zap-cfg overlay-url $frepo`
+    REPO=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} overlay-url $frepo`
     /usr/bin/curl -f -s -o ${CFGDIR}/repositories/${frepo}.overlays.tmp ${REPO}/catalog
     if [ -s ${CFGDIR}/repositories/${frepo}.overlays.tmp ]; then
 	mv ${CFGDIR}/repositories/${frepo}.overlays ${CFGDIR}/repositories/${frepo}.overlays.bak
 	mv ${CFGDIR}/repositories/${frepo}.overlays.tmp ${CFGDIR}/repositories/${frepo}.overlays
 	awk -F'|' '{print $1,$2}' ${CFGDIR}/repositories/${frepo}.overlays | while read novl nver
 	do
-	    iver=`${ZAPLIBDIR}/overlay-version $novl`
+	    iver=`${ZAPLIBDIR}/overlay-version ${CTXARGS} $novl`
 	    if [ "X${nver}" != "X${iver}" ]; then
 		/usr/bin/curl -f -s -o ${ODIR}/${novl}.ovl.tmp ${REPO}/${novl}.ovl
 		/usr/bin/curl -f -s -o ${ODIR}/${novl}.pkgs.tmp ${REPO}/${novl}.pkgs
@@ -35,7 +54,7 @@ refresh_repo() {
 
 case $# in
 0)
-	for repo in `${ZAPLIBDIR}/zap-cfg list-overlay-repos`
+	for repo in `${ZAPLIBDIR}/zap-cfg ${CTXARGS} list-overlay-repos`
 	do
 	    refresh_repo $repo
 	done
@@ -52,5 +71,5 @@ esac
 # if anything changed, refresh the catalog as well
 #
 if [ "X${UPDATED}" != "Xno" ]; then
-    ${ZAPLIBDIR}/refresh-catalog
+    ${ZAPLIBDIR}/refresh-catalog ${CTXARGS}
 fi
diff --git a/usr/lib/zap/retrieve-pkg b/usr/lib/zap/retrieve-pkg
--- a/usr/lib/zap/retrieve-pkg
+++ b/usr/lib/zap/retrieve-pkg
@@ -2,13 +2,26 @@
 
 ZAPLIBDIR="/usr/lib/zap"
 
-CACHE_DIR=`${ZAPLIBDIR}/zap-cfg cache-dir`
+case $1 in
+-C)
+	DESTROOT="$2"
+	CTXARGS="-C ${DESTROOT}"
+	shift
+	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	;;
+esac
+
+CACHE_DIR=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir`
 
 for pkg in $*
 do
-    ${ZAPLIBDIR}/get-version $pkg | read fpkg frepo
+    ${ZAPLIBDIR}/get-version ${CTXARGS} $pkg | read fpkg frepo
     if [ -n "$frepo" ]; then
-	REPO=`${ZAPLIBDIR}/zap-cfg repo-url $frepo`
+	REPO=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} repo-url $frepo`
 	echo "Trying to fetch ${REPO}/${fpkg}.zap"
 	/usr/bin/curl -f -s -o ${CACHE_DIR}/${fpkg}.zap ${REPO}/${fpkg}.zap
     fi
diff --git a/usr/lib/zap/update-overlay b/usr/lib/zap/update-overlay
--- a/usr/lib/zap/update-overlay
+++ b/usr/lib/zap/update-overlay
@@ -3,9 +3,27 @@
 ONAME=""
 ZAPLIBDIR="/usr/lib/zap"
 ODIR="/var/sadm/overlays"
+INSTODIR="S{ODIR}"
+CFGODIR="${ODIR}"
 PKGARGS=""
 DESTROOT=""
 SRCARGS=""
+
+case $1 in
+-C)
+	DESTROOT="$2"
+	PKGARGS="-R ${DESTROOT}"
+	CTXARGS="-C ${DESTROOT}"
+	shift
+	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	CFGODIR="${DESTROOT}/${ODIR}"
+	INSTODIR="${DESTROOT}/${ODIR}"
+	;;
+esac
 
 case $1 in
 -R)
@@ -17,6 +35,7 @@ case $1 in
 	    echo "ERROR: alternate root $DESTROOT doesn't exist"
 	    exit 1
 	fi
+	INSTODIR="${DESTROOT}/${ODIR}"
 	;;
 esac
 
@@ -39,24 +58,20 @@ case $# in
 	ONAME="$1"
 	;;
 *)
-	echo "Usage: $0 [-R alt-root] [-s pkg_source] overlay | -a"
+	echo "Usage: $0 [-R|-C alt-root] [-s pkg_source] overlay | -a"
 	exit 1
 	;;
 esac
-
-#
-# OK, we're in the installer
-#
 
 #
 # -a means all (installed) overlays
 #
 case $ONAME in
 -a)
-	cd ${DESTROOT}/${ODIR}/installed
+	cd ${INSTODIR}/installed
 	for novl in *
 	do
-	    ${ZAPLIBDIR}/update-overlay ${PKGARGS} ${SRCARGS} ${novl}
+	    ${ZAPLIBDIR}/update-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
 	done
 	exit 0
 	;;
@@ -66,13 +81,13 @@ esac
 # if not installed, just exit
 # if someone has messed with packages behind our back, they suffer
 #
-if [ ! -f ${DESTROOT}/${ODIR}/installed/${ONAME} ]; then
+if [ ! -f ${INSTODIR}/installed/${ONAME} ]; then
     exit 0
 fi
 
-PLIST="${ODIR}/${ONAME}.pkgs"
+PLIST="${CFGODIR}/${ONAME}.pkgs"
 if [ ! -f "${PLIST}" ]; then
-    echo "ERROR: package list missing"
+    echo "ERROR: package list for overlay ${ONAME} missing"
     exit 1
 fi
 
@@ -80,10 +95,10 @@ fi
 # install dependent overlays, if any
 # just in case the overlay dependencies changed
 #
-OVL="${ODIR}/${ONAME}.ovl"
+OVL="${CFGODIR}/${ONAME}.ovl"
 for novl in `/usr/bin/grep '^REQUIRES=' ${OVL} | /usr/bin/sed s:REQUIRES=::`
 do
-    ${ZAPLIBDIR}/install-overlay ${PKGARGS} ${SRCARGS} ${novl}
+    ${ZAPLIBDIR}/install-overlay ${CTXARGS} ${PKGARGS} ${SRCARGS} ${novl}
 done
 
-${ZAPLIBDIR}/update-package ${PKGARGS} ${SRCARGS} `cat ${PLIST}`
+${ZAPLIBDIR}/update-package ${CTXARGS} ${PKGARGS} ${SRCARGS} `cat ${PLIST}`
diff --git a/usr/lib/zap/update-package b/usr/lib/zap/update-package
--- a/usr/lib/zap/update-package
+++ b/usr/lib/zap/update-package
@@ -12,7 +12,22 @@
 # always show as needing update, so updates are explicitly disabled for oi
 #
 ZAPLIBDIR="/usr/lib/zap"
-CACHE_DIR=`${ZAPLIBDIR}/zap-cfg cache-dir`
+
+case $1 in
+-C)
+	DESTROOT="$2"
+	PKGARGS="-R ${DESTROOT}"
+	CTXARGS="-C ${DESTROOT}"
+	shift
+	shift
+	if [ ! -d "$DESTROOT" ]; then
+	    echo "ERROR: alternate root $DESTROOT doesn't exist"
+	    exit 1
+	fi
+	;;
+esac
+
+CACHE_DIR=`${ZAPLIBDIR}/zap-cfg ${CTXARGS} cache-dir`
 
 case $1 in
 -R)
@@ -44,7 +59,7 @@ esac
 for pkg in $*
 do
     IVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
-    AFVERSION=`${ZAPLIBDIR}/get-version $pkg`
+    AFVERSION=`${ZAPLIBDIR}/get-version ${CTXARGS} $pkg`
     AVERSION=${AFVERSION% *}
     AREPO=${AFVERSION#* }
     RVERSION=${AVERSION#*.}
@@ -54,11 +69,11 @@ do
 	else
 	    echo "Package $pkg is at version $IVERSION and needs updating to $AVERSION"
 	    if [ ! -f ${CACHE_DIR}/${AVERSION}.zap ]; then
-		${ZAPLIBDIR}/retrieve-pkg ${pkg}
+		${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} ${pkg}
 	    fi
 	    if [ -f ${CACHE_DIR}/${AVERSION}.zap ]; then
 		${ZAPLIBDIR}/delpkg ${PKGARGS} $pkg
-		${ZAPLIBDIR}/install-pkg ${PKGARGS} ${SRCARGS} $pkg
+		${ZAPLIBDIR}/install-pkg ${CTXARGS} ${PKGARGS} ${SRCARGS} $pkg
 	    fi
 	    NVERSION=`${ZAPLIBDIR}/pkgversion ${PKGARGS} $pkg`
 	    if [ "X${NVERSION}" = "X${RVERSION}" ]; then
diff --git a/usr/lib/zap/zap b/usr/lib/zap/zap
--- a/usr/lib/zap/zap
+++ b/usr/lib/zap/zap
@@ -11,30 +11,52 @@ case $# in
 	;;
 esac
 
+#
+# global context switch comes before the subcommand
+# will force all configuration to be relative to the alternate root
+#
 case $1 in
+-C)
+	ALTROOT="$2"
+	CTXARGS="-C ${ALTROOT}"
+	PKGARGS="-R ${ALTROOT}"
+	shift
+	shift
+	if [ ! -d "$ALTROOT" ]; then
+	    echo "ERROR: alternate root $ALTROOT doesn't exist"
+	    exit 1
+	fi
+	;;
+esac
+
+case $1 in
+upgrade)
+	shift
+	exec ${ZAPLIBDIR}/upgrade $*
+	;;
 retrieve)
 	shift
-	exec ${ZAPLIBDIR}/retrieve-pkg $*
+	exec ${ZAPLIBDIR}/retrieve-pkg ${CTXARGS} $*
 	;;
 install)
 	shift
-	exec ${ZAPLIBDIR}/install-pkg $*
+	exec ${ZAPLIBDIR}/install-pkg ${CTXARGS} $*
 	;;
 update)
 	shift
-	exec ${ZAPLIBDIR}/update-package $*
+	exec ${ZAPLIBDIR}/update-package ${CTXARGS} $*
 	;;
 uninstall)
 	shift
-	exec ${ZAPLIBDIR}/delpkg $*
+	exec ${ZAPLIBDIR}/delpkg ${PKGARGS} $*
 	;;
 install-overlay)
 	shift
-	exec ${ZAPLIBDIR}/install-overlay $*
+	exec ${ZAPLIBDIR}/install-overlay ${CTXARGS} $*
 	;;
 update-overlay)
 	shift
-	exec ${ZAPLIBDIR}/update-overlay $*
+	exec ${ZAPLIBDIR}/update-overlay ${CTXARGS} $*
 	;;
 uninstall-overlay)
 	shift
@@ -46,7 +68,7 @@ verify-overlay)
 	;;
 list-packages)
 	shift
-	exec /usr/bin/pkginfo $*
+	exec /usr/bin/pkginfo ${PKGARGS} $*
 	;;
 list-overlays)
 	shift
@@ -54,11 +76,11 @@ list-overlays)
 	;;
 refresh-overlays)
 	shift
-	exec ${ZAPLIBDIR}/refresh-overlays $*
+	exec ${ZAPLIBDIR}/refresh-overlays ${CTXARGS} $*
 	;;
 describe-package)
 	shift
-	exec /usr/bin/pkginfo -l $*
+	exec /usr/bin/pkginfo ${PKGARGS} -l $*
 	;;
 describe-overlay)
 	shift
@@ -66,7 +88,7 @@ describe-overlay)
 	;;
 refresh-catalog)
 	shift
-	exec ${ZAPLIBDIR}/refresh-catalog $*
+	exec ${ZAPLIBDIR}/refresh-catalog ${CTXARGS} $*
 	;;
 create-zone)
 	shift
diff --git a/usr/lib/zap/zap-cfg b/usr/lib/zap/zap-cfg
--- a/usr/lib/zap/zap-cfg
+++ b/usr/lib/zap/zap-cfg
@@ -9,6 +9,26 @@ CFGDIR="/etc/zap"
 CACHE_DIR="/var/zap/cache"
 CACHE_CFG="${CFGDIR}/cache_dir"
 
+#
+# global context switch
+# will force all configuration to be relative to the alternate root
+#
+case $1 in
+-C)
+	ALTROOT="$2"
+	CTXARGS="-C ${ALTROOT}"
+	shift
+	shift
+	if [ ! -d "$ALTROOT" ]; then
+	    echo "ERROR: alternate root $ALTROOT doesn't exist"
+	    exit 1
+	fi
+	CFGDIR="${ALTROOT}/${CFGDIR}"
+	CACHE_DIR="${ALTROOT}/${CACHE_DIR}"
+	CACHE_CFG="${CFGDIR}/cache_dir"
+	;;
+esac
+
 case $1 in
 list-pkg-repos)
 	if [ -f ${CFGDIR}/repo.list ]; then
